# Generated by Django 4.2.3 on 2023-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0004_rename_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.JSONField(blank=True),
        ),
    ]
