# Generated by Django 4.2.3 on 2023-08-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0008_objeto_wallet_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='dueño',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='foto',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
