# Generated by Django 4.2.3 on 2023-08-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0011_alter_objeto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
