# Generated by Django 4.2.3 on 2023-08-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0012_objeto_etiquetas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objeto',
            old_name='dueño',
            new_name='propietario',
        ),
    ]
