# Generated by Django 4.2.3 on 2023-08-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0013_rename_dueño_objeto_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='carrito',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
