# Generated by Django 4.2.3 on 2023-08-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0014_alter_wallet_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='carrito',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
