# Generated by Django 4.2.3 on 2023-08-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0015_alter_wallet_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='carrito',
        ),
    ]
